from setuptools import setup, find_packages


with open("README.md", "r") as fh:
    long_description = fh.read()


setup(name='wss_extract',
      version='0.1.0',
      description='Gets sentiment from online tools',
      long_description=long_description,
      long_description_content_type="text/markdown",
      author='Andrew Moore',
      author_email='andrew.p.moore94@gmail.com',
      license='MIT',
      install_requires=[
          'atomicwrites==1.1.5',
          'attrs==18.1.0',
          'backcall==0.1.0',
          'beautifulsoup4==4.5.1',
          'bleach==2.1.3',
          'cachetools==2.1.0',
          'decorator==4.3.0',
          'entrypoints==0.2.3',
          'html5lib==1.0.1',
          'ipykernel==4.8.2',
          'ipython==6.4.0',
          'ipython-genutils==0.2.0',
          'ipywidgets==7.2.1',
          'Jinja2==2.10',
          'jsonschema==2.6.0',
          'jupyter==1.0.0',
          'jupyter-client==5.2.3',
          'jupyter-console==5.2.0',
          'jupyter-core==4.4.0',
          'MarkupSafe==1.0',
          'mistune==0.8.3',
          'more-itertools==4.2.0',
          'nbconvert==5.3.1',
          'nbformat==4.4.0',
          'notebook==5.5.0',
          'pandocfilters==1.4.2',
          'pexpect==4.6.0',
          'pickleshare==0.7.4',
          'pluggy==0.6.0',
          'prompt-toolkit==1.0.15',
          'ptyprocess==0.5.2',
          'py==1.5.3',
          'Pygments==2.2.0',
          'pytest==3.6.1',
          'python-dateutil==2.7.3',
          'pyzmq==17.0.0',
          'qtconsole==4.3.1',
          'reppy==0.4.9',
          'requests==2.12.4',
          'robobrowser==0.5.3',
          'Send2Trash==1.5.0',
          'simplegeneric==0.8.1',
          'six==1.10.0',
          'terminado==0.8.1',
          'testpath==0.3.1',
          'tornado==5.0.2',
          'traitlets==4.3.2',
          'wcwidth==0.1.7',
          'webencodings==0.5.1',
          'Werkzeug==0.11.11',
          'widgetsnbextension==3.2.1'
      ],
      python_requires='>=3.6',
      packages=find_packages())
